(function(g){var window=this;var $za=function(a,b){return g.Ob(a,b)},Z5=function(a,b,c){a.A.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.fn(a.A,b,c)},aAa=function(a,b){var c=[];
g.lk(b,function(d){try{var e=g.fo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.eo(e)&&c.push(d)},a);
return c},bAa=function(a,b){var c=aAa(a,b);
(0,g.y)(c,function(d){g.fo.prototype.remove.call(this,d)},a)},cAa=function(a){if(a.fd){if(a.fd.locationOverrideToken)return{locationOverrideToken:a.fd.locationOverrideToken};
if(null!=a.fd.latitudeE7&&null!=a.fd.longitudeE7)return{latitudeE7:a.fd.latitudeE7,longitudeE7:a.fd.longitudeE7}}return null},dAa=function(a,b){g.fb(a,b)||a.push(b)},b6=function(a){var b=0,c;
for(c in a)b++;return b},eAa=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},c6=function(){},fAa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gAa=function(a){if(a.Xd&&"function"==typeof a.Xd)return a.Xd();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Kb(a)},hAa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.df&&"function"==typeof a.df)var c=a.df();else if(a.Xd&&"function"==typeof a.Xd)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Lb(a);d=gAa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},iAa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&(e.u=d);return e},d6=function(a,b){g.Mo[a]=!0;
var c=g.Ko();c&&c.publish.apply(c,arguments);g.Mo[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Rm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jAa(this,a.capabilities||""),kAa(this,a.experiments||""))},jAa=function(a,b){a.capabilities.clear();
(0,g.ye)(b.split(","),g.Sa($za,lAa)).forEach(function(c){a.capabilities.add(c)})},kAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},mAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nAa=function(a){return new f6(a)},oAa=function(a){return Array.isArray(a)?(0,g.Ic)(a,nAa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return Array.isArray(a)?"["+(0,g.Ic)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},pAa=function(a){return(0,g.Ic)(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.cb(a,function(c){return g6(c,b)})},qAa=function(){var a=(0,g.Ys)();
a&&bAa(a,a.o.Vh(!0))},m6=function(){var a=g.at("yt-remote-connected-devices")||[];
g.yb(a);return a},rAa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},sAa=function(a){g.$s("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.at("yt-remote-device-id");a||(a=j6(),g.$s("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.fb(a,b);g.ct()&&g.Ab(a,b);a=rAa(a);if(g.gb(a))try{g.xq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.yq("remote_sid",a.join(","),-1)}catch(c){}},tAa=function(){return g.at("yt-remote-session-browser-channel")},uAa=function(){return g.at("yt-remote-local-screens")||[]},vAa=function(){g.$s("yt-remote-lounge-token-expiration",!0,86400)},wAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Ic)(uAa(),function(d){return d.loungeToken}),c=(0,g.Ic)(a,function(d){return d.loungeToken});
(0,g.yi)(c,function(d){return!g.fb(b,d)})&&vAa();
g.$s("yt-remote-local-screens",a,31536E3)},xAa=function(a,b){g.$s("yt-remote-session-browser-channel",a);
g.$s("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.fb(c,d)||c.push(d);sAa(c);p6()},q6=function(a){a||(g.bt("yt-remote-session-screen-id"),g.bt("yt-remote-session-video-id"));
p6();a=m6();g.lb(a,o6());sAa(a)},yAa=function(){if(!r6){var a=g.lo();
a&&(r6=new g.Wn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},zAa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},AAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?BAa(a.shift(),function(){s6(a)}):t6()},CAa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},BAa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=AAa();
a&&a(!1,"No cast extension found")},EAa=function(){if(DAa){var a=2,b=AAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;BAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},FAa=function(){EAa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.A.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Nd=b;this.C=(0,g.x)(this.MG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},v6=function(a,b,c){g.A.call(this);
this.B=null!=c?a.bind(c):a;this.Nd=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},w6=function(a){a.Ka=g.Yf(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,w6(a))},a.Nd);
var b=a.A;a.A=null;a.B.apply(null,b)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return fAa(a)},y6=function(){},z6=function(){},GAa=function(){},IAa=function(a){return(a=HAa(a))?new ActiveXObject(a):new XMLHttpRequest},HAa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.x1(this);this.u=new g.Xf;this.u.setInterval(250)},KAa=function(a,b,c){a.Sl=1;
a.Yh=$5(b.clone());a.hk=c;a.F=!0;JAa(a,null)},B6=function(a,b,c,d,e){a.Sl=1;
a.Yh=$5(b.clone());a.hk=null;a.F=c;e&&(a.yD=!1);JAa(a,d)},JAa=function(a,b){a.Ml=(0,g.E)();
C6(a);a.Si=a.Yh.clone();a6(a.Si,"t",a.G);a.xo=0;a.gd=a.o.zt(a.o.ho()?b:null);0<a.hu&&(a.Cr=new v6((0,g.x)(a.wE,a,a.gd),a.hu));a.B.ma(a.gd,"readystatechange",a.sO);var c=a.Aj?g.Ub(a.Aj):{};a.hk?(a.ws="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.gd.send(a.Si,a.ws,a.hk,c)):(a.ws="GET",a.yD&&!g.ne&&(c.Connection="close"),a.gd.send(a.Si,a.ws,null,c));a.o.Uf(1)},NAa=function(a,b,c){for(var d=!0;!a.hj&&a.xo<c.length;){var e=LAa(a,c);
if(e==D6){4==b&&(a.ni=4,E6(15),d=!1);break}else if(e==MAa){a.ni=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.ni=1,E6(17),d=!1);a.dg=a.dg&&d;d||(G6(a),H6(a))},LAa=function(a,b){var c=a.xo,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return MAa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.xo=d+c;return e},PAa=function(a,b){a.Ml=(0,g.E)();
C6(a);var c=b?window.location.hostname:"";a.Si=a.Yh.clone();Z5(a.Si,"DOMAIN",c);Z5(a.Si,"t",a.G);try{a.jg=new ActiveXObject("htmlfile")}catch(n){G6(a);a.ni=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in I6)h=I6[l];else if(l in OAa)h=I6[l]=OAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
I6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Zc(g.ec("b/12014412"),d+"</body></html>");a.jg.open();a.jg.write(g.Vc(c));a.jg.close();a.jg.parentWindow.m=(0,g.x)(a.HN,a);a.jg.parentWindow.d=(0,g.x)(a.CC,a,!0);a.jg.parentWindow.rpcClose=(0,g.x)(a.CC,a,!1);c=a.jg.createElement("DIV");a.jg.parentWindow.document.body.appendChild(c);d=g.Dc(a.Si.toString());d=g.gd(g.zc(d));d=g.Zc(g.ec("b/12014412"),'<iframe src="'+d+'"></iframe>');g.$c(c,d);a.o.Uf(1)},C6=function(a){a.ax=(0,g.E)()+a.C;
QAa(a,a.C)},QAa=function(a,b){if(null!=a.Zl)throw Error("WatchDog timer not null");
a.Zl=J6((0,g.x)(a.QN,a),b)},K6=function(a){a.Zl&&(g.v.clearTimeout(a.Zl),a.Zl=null)},H6=function(a){a.o.Fz()||a.hj||a.o.Zp(a)},G6=function(a){K6(a);
g.Ke(a.Cr);a.Cr=null;a.u.stop();g.Eua(a.B);if(a.gd){var b=a.gd;a.gd=null;b.abort();b.dispose()}a.jg&&(a.jg=null)},F6=function(a,b){try{a.o.tC(a,b),a.o.Uf(4)}catch(c){}},SAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;RAa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){SAa(a,b,c,d,f)},f)})}},RAa=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
eAa(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},TAa=function(a){this.o=a;
this.u=new y6},UAa=function(a){var b=M6(a.o,a.nm,"/mail/images/cleardot.gif");
$5(b);SAa(b.toString(),5E3,(0,g.x)(a.LF,a),3,2E3);a.Uf(1)},O6=function(a){var b=a.o.M;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Be=new A6(a,void 0,void 0,void 0),a.Be.Aj=a.fu,b=a.o,b=M6(b,b.ho()?a.Rm:null,a.gu),E6(5),!g.le||g.Qd(10))a6(b,"TYPE","xmlhttp"),B6(a.Be,b,!1,a.Rm,!1);else{a6(b,"TYPE","html");var c=a.Be;a=!!a.Rm;c.Sl=3;c.Yh=$5(b.clone());PAa(c,a)}},P6=function(a){g.mf.call(this);
this.headers=new g.Rm;this.T=a||null;this.A=!1;this.U=this.o=null;this.ga=this.M="";this.F=0;this.B="";this.C=this.aa=this.I=this.Y=!1;this.G=0;this.N=null;this.fa="";this.R=this.Z=!1},VAa=function(a){return g.le&&g.Pd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},WAa=function(a){return"content-type"==a.toLowerCase()},YAa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;XAa(a);Q6(a)},XAa=function(a){a.Y||(a.Y=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},$Aa=function(a){if(a.A&&"undefined"!=typeof g.C1)if(a.U[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.I&&4==R6(a))g.Yf(a.pC,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.qd(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!ZAa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";XAa(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){aBa(a);
var c=a.o,d=a.U[0]?g.Ka:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},aBa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.ga+" "+a.M+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new y6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},bBa=function(a,b){this.o=a;
this.map=b;this.context=null},cBa=function(a){g.Me.call(this,"statevent",a)},dBa=function(a,b){g.Me.call(this,"timingevent",a);
this.size=b},eBa=function(a){g.Me.call(this,"serverreachability",a)},hBa=function(a){fBa(a);
if(3==a.o){var b=a.Bn++,c=a.Ip.clone();Z5(c,"SID",a.A);Z5(c,"RID",b);Z5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.A,b,void 0);b.Sl=2;b.Yh=$5(c.clone());eAa(new Image,b.Yh.toString());b.Ml=(0,g.E)();C6(b)}gBa(a)},iBa=function(a){a.kG(1,0);
a.Ip=M6(a,null,a.eu);W6(a)},fBa=function(a){a.bi&&(a.bi.abort(),a.bi=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.ah&&(g.v.clearTimeout(a.ah),a.ah=null);X6(a);a.ne&&(a.ne.cancel(),a.ne=null);a.gi&&(g.v.clearTimeout(a.gi),a.gi=null)},jBa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new bBa(a.sK++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.ne||a.gi||(a.gi=J6((0,g.x)(a.BC,a),0),a.Qk=0)},lBa=function(a,b){if(1==a.o){if(!b){a.Bn=Math.floor(1E5*Math.random());
var c=a.Bn++,d=new A6(a,"",c,void 0);d.Aj=a.Xk;var e=Y6(a),f=a.Ip.clone();Z5(f,"RID",c);Z5(f,"CVER","1");V6(a,f);KAa(d,f,e);a.ne=d;a.o=2}}else 3==a.o&&(b?kBa(a,b):0==a.u.length||a.ne||kBa(a))},kBa=function(a,b){if(b)if(6<a.ij){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Bn-1;var d=Y6(a)}else c=b.I,d=b.hk;else c=a.Bn++,d=Y6(a);var e=a.Ip.clone();Z5(e,"SID",a.A);Z5(e,"RID",c);Z5(e,"AID",a.ol);V6(a,e);c=new A6(a,a.A,c,a.Qk+1);c.Aj=a.Xk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ne=c;KAa(c,e,d)},V6=function(a,b){if(a.Kd){var c=a.Kd.dz();
c&&g.Cb(c,function(d,e){Z5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.ij&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.ij?e:f-d;try{g.Cb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},mBa=function(a){a.Ec||a.ah||(a.G=1,a.ah=J6((0,g.x)(a.AC,a),0),a.Ck=0)},Z6=function(a){if(a.Ec||a.ah||3<=a.Ck)return!1;
a.G++;a.ah=J6((0,g.x)(a.AC,a),nBa(a,a.Ck));a.Ck++;return!0},N6=function(a,b,c){a.ts=c;
a.ug=b.rh;a.F||iBa(a)},X6=function(a){null!=a.mj&&(g.v.clearTimeout(a.mj),a.mj=null)},nBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Kd&&(c=null);var d=(0,g.x)(a.bP,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),$5(c));RAa(c.toString(),1E4,d)}else E6(2);oBa(a,b)},oBa=function(a,b){a.o=0;
a.Kd&&a.Kd.ry(b);gBa(a);fBa(a)},gBa=function(a){a.o=0;
a.ug=-1;if(a.Kd)if(0==a.B.length&&0==a.u.length)a.Kd.it();else{g.pb(a.B);var b=g.pb(a.u);a.B.length=0;a.u.length=0;a.Kd.it(b)}},M6=function(a,b,c){var d=g.bn(c);
if(""!=d.o)b&&g.Wm(d,b+"."+d.o),g.Xm(d,d.B);else{var e=window.location;d=iAa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Gm&&g.Cb(a.Gm,function(f,h){Z5(d,h,f)});
Z5(d,"VER",a.ij);V6(a,d);return d},J6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new cBa(a7,a))},pBa=function(){},qBa=function(){this.o=[];
this.u=[]},rBa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.H(this.AN,0,this);g.C(this,this.o);this.Nd=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},c7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.N=a;this.F=b;this.A=new g.Vn;this.u=new b7(this.GO,this);this.o=null;this.Sc=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.U=c;this.R=d},sBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ts,sessionId:a.o.A,arrayId:a.o.ol}},tBa=function(a,b){a.I=b||0;
a.u.stop();d7(a);a.o&&(3==a.o.o&&lBa(a.o),hBa(a.o));a.I=0},e7=function(a){return!!a.o&&3==a.o.o},d7=function(a){if(a.o){var b=a.R(),c=a.o.Xk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.o.Xk=c}},uBa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},f7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.qd(4,a))||"";b&&(this.port=":"+b);this.domain=g.rd(a)||"";a=g.Oc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.wc(a,"10.0")&&(this.u=!1))},g7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Bd(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.B,d,!0),onError:g.Sa(a.A,e),Se:g.Sa(a.C,e)};c&&(a.Gb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.rq(b,a)},yBa=function(){var a=vBa;
wBa();i7.push(a);xBa(i7)},j7=function(a,b){wBa();
var c=i7,d=zBa(a,String(b));g.gb(c)?ABa(d):(xBa(c),(0,g.y)(c,function(e){e(d)}))},wBa=function(){i7||(i7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",i7,void 0))},ABa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},xBa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},zBa=function(a,b){var c=((0,g.E)()-BBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.O.call(this);
this.F=a;this.screens=[]},CBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},DBa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.ye)(a.screens,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=CBa(a,b[d])||c;return c},EBa=function(a,b){var c=a.screens.length;
a.screens=(0,g.ye)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.O.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.Ka=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;p7(this);this.info("Initializing with "+i6(this.screens))},FBa=function(a){if(a.screens.length){var b=(0,g.Ic)(a.screens,function(d){return d.id}),c=g7(a.u,"/pairing/get_lounge_token_batch");
h7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.XG,a),(0,g.x)(a.WG,a))}},p7=function(a){var b=oAa(uAa());
b=(0,g.ye)(b,function(c){return!c.uuid});
return DBa(a,b)},r7=function(a,b){wAa((0,g.Ic)(a.screens,mAa));
b&&vAa()},t7=function(a,b){g.O.call(this);
this.F=b;var c=g.at("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;s7("Initialized with "+g.Nk(this.o))},GBa=function(a,b,c){var d=g7(a.C,"/pairing/get_screen_availability");
h7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},u7=function(a,b){a:if(b6(b)!=b6(a.o))var c=!1;
else{c=g.Lb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Nk(a.o)),a.o=b,a.S("screenChange"));HBa(a)},v7=function(a){isNaN(a.A)||g.Jo(a.A);
a.A=g.Ho((0,g.x)(a.Yv,a),0<a.B&&a.B<(0,g.E)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},IBa=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.qc("Requesting availability of screen w/o lounge token.")});
return b},HBa=function(a){a=g.Lb(g.Db(a.o,function(b){return b}));
g.yb(a);a.length?g.$s("yt-remote-online-screen-ids",a.join(","),60):g.bt("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};JBa(this)},LBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Me();if(h=(c?l6(h,c):null)||l6(h,b)){h.uuid=b;var l=x7(a,h);GBa(a.o,l,function(m){e(m?l:null)})}else c?KBa(a,c,(0,g.x)(function(m){var n=x7(this,new f6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));GBa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},MBa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},KBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Gb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.rq(g7(a.C,"/pairing/get_lounge_token_batch"),e)},NBa=function(a){a.screens=a.u.Me();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.screens))},JBa=function(a){y7(a);
a.u=new q7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.eH,a));NBa(a);a.A=oAa(g.at("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+i6(a.A));a.o=new t7(a.C,(0,g.x)(a.Me,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.$s("yt-remote-automatic-screen-cache",(0,g.Ic)(a.A,mAa)));y7(a);a.B[b.uuid]=b.id;g.$s("yt-remote-device-id-map",a.B,31536E3);return b},y7=function(a){a.B=g.at("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.O.call(this);
this.U=c;this.M=a;this.o=b;this.I=null},A7=function(a,b){j7(a.U,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.HP,this);this.B=(0,g.x)(this.YN,this);this.A=g.Ho((0,g.x)(function(){OBa(this,null)},this),12E4)},PBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Nk(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.x)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Nk(b))},OBa=function(a,b){g.Jo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.sr,a),d=(0,g.x)(a.Re,a);a.yz(b,c,d,5)}}else a.Re(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.T=c;this.B=null;this.F=g.Ka;this.C=NaN;this.R=(0,g.x)(this.KP,this);this.u=g.Ka},QBa=function(a){a.u=a.M.DE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Ka;
this.sr(b)},a),(0,g.x)(function(b){this.u=g.Ka;
this.Re(b)},a))},RBa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}yAa()&&(b.env_useStageMdx=1);return g.zd(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.u=g.Ho((0,g.x)(this.pl,this,null),150)},E7=function(a,b,c,d){g.O.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.OM,this)},SBa=function(a,b){return b?g.cb(a.A,function(c){return g6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},vBa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.C||!!a.A.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.Ke(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.yC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.pl(null)):a.S("yt-remote-cast2-session-change",null))},TBa=function(a){var b=a.u.CE(),c=a.o&&a.o.o;
a=(0,g.Ic)(b,function(d){c&&g6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=SBa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},ZBa=function(a,b,c,d,e,f,h){UBa()?VBa(b,e,f,h)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?WBa(a,c):(window.__onGCastApiAvailable=function(l,m){l?WBa(a,c):(K7("Failed to load cast API: "+m),L7(!1),J7(!1),g.bt("yt-remote-cast-available"),g.bt("yt-remote-cast-receiver"),XBa(),c(!1))},d?g.To("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?FAa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(EAa(),s6(YBa.map(CAa))))):I7("Cannot initialize because not running Chrome")},XBa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);$Ba(!1);g.Po(N7);N7.length=0},O7=function(){return!!g.at("yt-remote-cast-installed")},aCa=function(){var a=g.at("yt-remote-cast-receiver");
return a?a.friendlyName:null},bCa=function(){I7("clearCurrentReceiver");
g.bt("yt-remote-cast-receiver")},cCa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.Oo("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},UBa=function(){var a=0<=g.Oc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Sw||a},dCa=function(a,b){M7().init(a,b)},VBa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.$s("yt-remote-cast-available",f);d6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.$s("yt-remote-cast-receiver",f);d6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.$s("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+h6(f));
f||g.bt("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},WBa=function(a,b){L7(!0);
J7(!1);dCa(a,function(c){c?($Ba(!0),g.Qo("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.bt("yt-remote-cast-available"),g.bt("yt-remote-cast-receiver"),XBa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.$s("yt-remote-cast-installed",a)},P7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},$Ba=function(a){I7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.vg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.vg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},U7=function(a){return a.ub()?((0,g.E)()-a.F)/1E3:0},V7=function(a,b){a.G=b;
a.F=(0,g.E)()},W7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Vb(a.o);b.hasPrevious=a.vg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},$7=function(a,b){g.O.call(this);
this.o=0;this.B=a;this.F=[];this.C=new qBa;this.A=this.u=null;this.M=(0,g.x)(this.YK,this);this.G=(0,g.x)(this.Fn,this);this.I=(0,g.x)(this.XK,this);this.N=(0,g.x)(this.gL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ex,this),eCa(this))):c=3;0!=c&&(b?this.ex(c):g.Ho((0,g.x)(function(){this.ex(c)},this),0));
var d=cCa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},a8=function(a){return new S7(a.B.getPlayerContextData())},eCa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Sa(this.KM,b),this))},a)},fCa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);c8(a,d)},e8=function(a,b,c){a.B.sendMessage(b,c)},c8=function(a,b){fCa(a);
a.B.setPlayerContextData(Y7(b));eCa(a)},Z7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Fn(null));
a.A=b;a.A&&(j7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Fn(a.A.media[0]))},gCa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.x)(function(d){this.qc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.qc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.O.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.jb=this.o=null;this.Y=a;this.U.push(g.dp(window,"beforeunload",(0,g.x)(this.PG,this)));this.u=[];this.jb=new S7;this.T=b.id;this.o=hCa(this,c);this.o.subscribe("handlerOpened",this.cL,this);this.o.subscribe("handlerClosed",this.ZK,this);this.o.subscribe("handlerError",this.aL,this);this.o.subscribe("handlerMessage",this.bL,this);uBa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.jb.videoId;
g.ct()&&g.$s("yt-remote-session-video-id",d)},this)},h8=function(a){j7("conn",a)},hCa=function(a,b){return new c7(g7(a.Y,"/bc"),b,!1,function(){return a.zE()})},i8=function(a,b){a.S("proxyStateChange",b)},iCa=function(a){a.C=g.Ho((0,g.x)(function(){h8("Connecting timeout");
this.Lk(1)},a),2E4)},j8=function(a){g.Jo(a.C);
a.C=NaN},k8=function(a){g.Jo(a.N);
a.N=NaN},jCa=function(a){l8(a);
a.M=g.Ho((0,g.x)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.Jo(a.M);
a.M=NaN},lCa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&isNaN(a.C))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.wz()&&a.jb.reset(),i8(a,1),m8(a,"getNowPlaying"),kCa(a)):a.Lk(1)},mCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Rb(b.params)?a.jb.o=null:a.jb.o=b.params,a.S("remotePlayerChange"))},nCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;X7(a.jb,c,d);a.S("remoteQueueChange")},pCa=function(a,b){b.params=b.params||{};
nCa(a,b);oCa(a,b);a.S("autoplayDismissed")},oCa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.jb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.jb.playerState&&(c=-1E3);a.jb.playerState=c;c=Number(b.params.loadedTime);a.jb.M=isNaN(c)?0:c;c=Number(b.params.duration);a.jb.I=isNaN(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.jb.playerState?jCa(a):l8(a);a.S("remotePlayerChange")},qCa=function(a,b){if(-1E3!=
a.jb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.jb,isNaN(c)?0:c);a.S("remotePlayerChange")}},rCa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=parseInt(b.params.volume,10);a.jb.muted=c;a.S("remotePlayerChange")},sCa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},tCa=function(a,b){var c="true"==b.params.hasNext;
a.jb.vg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.S("previousNextChange")},kCa=function(a){g.Jo(a.I);
a.I=g.Ho((0,g.x)(a.Lk,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Nk(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.Md=a;this.o=[];this.o.push(this.Md.$_s("screenChange",(0,g.x)(this.FP,this)));this.o.push(this.Md.$_s("onlineScreenChange",(0,g.x)(this.oM,this)))},yCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;qAa();p6();o8||(o8=new f7(b?b.loungeApiHost:void 0),yAa()&&(o8.o="/api/loungedev"));p8||(p8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",p8,void 0));uCa();var c=q8();if(!c){var d=new w7(o8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);ZBa(a,d,function(m){m?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){d6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ja("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Nk(b)),t8.push(g.Oo("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")})),t8.push(g.Oo("yt-remote-cast2-receiver-selected",function(){u8(null);
d6("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.Oo("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.Oo("yt-remote-cast2-session-change",vCa)),t8.push(g.Oo("yt-remote-connection-change",function(m){m?R7(r8(),"YouTube TV"):v8()||(R7(null,null),bCa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.xo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),s8(" -- with channel params: "+
g.Nk(a)),wCa(a),c.start(),r8()||xCa())},ACa=function(){var a=zCa();
O7()&&g.at("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},zCa=function(){var a=q8().Md.$_gos();
var b=x8();b&&y8()&&(k6(a,b)||a.push(b));return pAa(a)},z8=function(){var a=BCa();
!a&&O7()&&aCa()&&(a={key:"cast-selector-receiver",name:aCa()});return a},BCa=function(){var a=zCa(),b=x8();
b||(b=v8());return g.cb(a,function(c){return b&&g6(b,c.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Me();return l6(b,a)},vCa=function(a){s8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.Ja("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},CCa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},DCa=function(){return g.Ja("yt.mdx.remote.connectData_")},u8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.Ja("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||CCa("");g.Ha("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.y)(p8,function(c){c(a)}),p8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},v8=function(){var a=g.ct();
if(!a)return null;var b=q8();if(!b)return null;b=b.Me();return l6(b,a)},B8=function(a,b){r8();
x8()&&x8();if(F8)G8=a;else{CCa(a.id);var c=new g8(o8,a,w8());c.connect(b,DCa());c.subscribe("beforeDisconnect",function(d){d6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){y8()&&(y8(),C8(null))});
C8(c)}},xCa=function(){var a=v8();
a?(s8("Resume connection to: "+h6(a)),B8(a,0)):(q6(),bCa(),s8("Skipping connecting because no session screen found."))},uCa=function(){var a=w8();
if(g.Rb(a)){a=o6();var b=g.at("yt-remote-session-name")||"",c=g.at("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},wCa=function(a){a?(g.$s("yt-remote-session-app",a.app),g.$s("yt-remote-session-name",a.name)):(g.bt("yt-remote-session-app"),g.bt("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},H8=function(a,b,c){g.A.call(this);
var d=this;this.module=a;this.H=b;this.ab=c;this.events=new g.ds(this);this.M=this.events.L(this.H,"onVolumeChange",this.aC);this.B=!1;this.suggestion=null;this.C=new g.aG(64);this.o=new g.H(this.ID,500,this);this.u=new g.H(this.JD,1E3,this);this.G=new u6(this.lP,0,this);this.A={};this.I=new g.H(this.mE,1E3,this);this.F=new v6(this.seekTo,1E3,this);this.N=g.Ka;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.PL);this.events.L(b,"captionschanged",this.WK);this.events.L(b,"captionssettingschanged",
this.MD);this.events.L(b,"videoplayerreset",this.tr);this.events.L(b,"mdxautoplaycancel",function(){d.ab.My()});
a=this.ab;a.ha();a.subscribe("proxyStateChange",this.sC,this);a.subscribe("remotePlayerChange",this.Mn,this);a.subscribe("remoteQueueChange",this.tr,this);a.subscribe("previousNextChange",this.oC,this);a.subscribe("nowAutoplaying",this.kC,this);a.subscribe("autoplayDismissed",this.KB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.MD();this.tr();this.Mn()},ECa=function(a){a.Yb(0);
a.o.stop();a.Qc(new g.aG(64))},J8=function(a,b){if(I8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Xb(c,b));a.ab.AE(a.H.getVideoData(1).videoId,c);a.A=a8(a.ab).o}},K8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.ab.playVideo(c.videoId,b,d,e,c.playerParams,c.kf,cAa(c));a.Qc(new g.aG(1))},FCa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Wz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},I8=function(a){return a8(a.ab).videoId===a.H.getVideoData(1).videoId},L8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"Learn more"},{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"OK"}]}]}]});this.o=new g.kO(this,250);this.learnMoreButton=
this.ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ca("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.o=new g.kO(this,250);this.cancelButton=this.ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ca("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},N8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.nM()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.kO(this,250);g.C(this,this.o);this.L(a,"presentingplayerstatechange",this.u);GCa(this,g.lM(a))},GCa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.OL("Error on $RECEIVER_NAME",c):b.ub()||g.T(b,4)?g.OL("Playing on $RECEIVER_NAME",c):g.OL("Connected to $RECEIVER_NAME",c);a.la("statustext",c);a.o.show()}else a.o.hide()},O8=function(a,b){g.FR.call(this,"Play on",0,a,b);
this.H=a;this.Ri={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},P8=function(a){g.QN.call(this,a);
this.Pf={key:j6(),name:"This computer"};this.ng=null;this.subscriptions=[];this.Lv=this.ab=null;this.Ri=[this.Pf];this.di=this.Pf;this.Ub=new g.aG(64);this.oA=0;this.md=-1;this.rl=null;this.Nn=this.Cq=!1;this.gk=this.Jl=null;if(!g.Ay(this.player.O())){a=this.player;var b=g.cN(a);b&&(b=b.xj())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.CN(a,b.element,4);this.Jl=new M8;g.C(this,this.Jl);g.CN(a,this.Jl.element,4);g.Q(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.rl=new L8,g.C(this,this.rl),g.CN(a,this.rl.element,4));this.Nn=!!v8();this.Cq=!!g.at("yt-remote-manual-pairing-warning-shown")}},Q8=function(a){a.gk&&(a.player.removeEventListener("presentingplayerstatechange",a.gk),a.gk=null)},HCa=function(a,b,c){a.Ub=c;
a.player.S("presentingplayerstatechange",new g.jG(c,b))},ICa=function(a,b,c){var d=!1;
1===b?d=!a.Nn:2===b&&(d=!a.Cq);d&&g.lG(c,8)&&(a.player.pauseVideo(),Q8(a))},R8=function(a,b){if(b.key!==a.di.key)if(b.key===a.Pf.key)A8();
else{if(a.rl&&!a.Cq&&b!==a.Pf&&"cast-selector-receiver"!==b.key&&g.Jy(a.player.O()))JCa(a);else{var c;(c=!g.Q(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Nn||!a.Jl);(c?0:g.Jy(a.player.O())||g.Ny(a.player.O()))&&KCa(a)}a.di=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Aa(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.kf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=cAa(c))&&(d.locationInfo=c);c=d}s8("Connecting to: "+g.Nk(b));"cast-selector-receiver"==b.key?(u8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&D8()&&r8()==b.key?d6("yt-remote-connection-change",!0):(A8(),u8(c||null),c=q8().Me(),(c=l6(c,b.key))&&B8(c,1))}},KCa=function(a){g.lM(a.player).ub()?a.player.pauseVideo():(a.gk=function(b){ICa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.gk));
a.Jl&&a.Jl.Zb();y8()||(F8=!0)},JCa=function(a){g.lM(a.player).ub()?a.player.pauseVideo():(a.gk=function(b){ICa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.gk));
a.rl&&a.rl.Zb();y8()||(F8=!0)},OAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},LCa={},lAa={mQ:"atp",fT:"ska",PS:"que",dS:"mus",eT:"sus",lR:"dsp",XS:"seq"},r6,n6="",DAa=zAa("loadCastFramework")||zAa("loadCastApplicationFramework"),YBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(u6,g.A);g.k=u6.prototype;g.k.LG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.E)()+this.Nd:this.Ka=g.Yf(this.C,this.Nd)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();u6.uc.X.call(this)};
g.k.MG=function(){this.A?(this.Ka=g.Yf(this.C,this.A-(0,g.E)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(v6,g.A);g.k=v6.prototype;g.k.CA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:w6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,w6(this))};
g.k.X=function(){g.A.prototype.X.call(this);this.stop()};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},HAa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ua(GAa,z6);S8=new GAa;g.k=A6.prototype;g.k.Aj=null;g.k.dg=!1;g.k.Zl=null;g.k.ax=null;g.k.Ml=null;g.k.Sl=null;g.k.Yh=null;g.k.Si=null;g.k.hk=null;g.k.gd=null;g.k.xo=0;g.k.jg=null;g.k.ws=null;g.k.ni=null;g.k.Sm=-1;g.k.yD=!0;g.k.hj=!1;g.k.hu=0;g.k.Cr=null;var MAa={},D6={};g.k=A6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.sO=function(a){a=a.target;var b=this.Cr;b&&3==R6(a)?b.CA():this.wE(a)};
g.k.wE=function(a){try{if(a==this.gd)a:{var b=R6(this.gd),c=this.gd.F,d=this.gd.getStatus();if(g.le&&!g.Qd(10)||g.ne&&!g.Pd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!T6(this.gd))break a;this.hj||4!=b||7==c||(8==c||0>=d?this.o.Uf(3):this.o.Uf(2));K6(this);var e=this.gd.getStatus();this.Sm=e;var f=T6(this.gd);(this.dg=200==e)?(4==b&&G6(this),this.F?(NAa(this,b,f),g.Ch&&this.dg&&3==b&&(this.B.ma(this.u,"tick",this.mO),this.u.start())):F6(this,f),this.dg&&!this.hj&&(4==b?this.o.Zp(this):(this.dg=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ni=3,E6(13)):(this.ni=0,E6(14)),G6(this),H6(this))}}catch(h){this.gd&&T6(this.gd)}finally{}};
g.k.mO=function(){var a=R6(this.gd),b=T6(this.gd);this.xo<b.length&&(K6(this),NAa(this,a,b),this.dg&&4!=a&&C6(this))};
g.k.HN=function(a){J6((0,g.x)(this.GN,this,a),0)};
g.k.GN=function(a){this.hj||(K6(this),F6(this,a),C6(this))};
g.k.CC=function(a){J6((0,g.x)(this.FN,this,a),0)};
g.k.FN=function(a){this.hj||(G6(this),this.dg=a,this.o.Zp(this),this.o.Uf(4))};
g.k.cancel=function(){this.hj=!0;G6(this)};
g.k.QN=function(){this.Zl=null;var a=(0,g.E)();0<=a-this.ax?(2!=this.Sl&&this.o.Uf(3),G6(this),this.ni=2,E6(18),H6(this)):QAa(this,this.ax-a)};
g.k.getLastError=function(){return this.ni};g.k=TAa.prototype;g.k.fu=null;g.k.Be=null;g.k.Dr=!1;g.k.Gz=null;g.k.Fp=null;g.k.Ju=null;g.k.gu=null;g.k.hf=null;g.k.rh=-1;g.k.Rm=null;g.k.nm=null;g.k.connect=function(a){this.gu=a;a=M6(this.o,null,this.gu);E6(3);this.Gz=(0,g.E)();var b=this.o.I;null!=b?(this.Rm=b[0],(this.nm=b[1])?(this.hf=1,UAa(this)):(this.hf=2,O6(this))):(a6(a,"MODE","init"),this.Be=new A6(this,void 0,void 0,void 0),this.Be.Aj=this.fu,B6(this.Be,a,!1,null,!0),this.hf=0)};
g.k.LF=function(a){if(a)this.hf=2,O6(this);else{E6(4);var b=this.o;b.ug=b.bi.rh;$6(b,9)}a&&this.Uf(2)};
g.k.zt=function(a){return this.o.zt(a)};
g.k.abort=function(){this.Be&&(this.Be.cancel(),this.Be=null);this.rh=-1};
g.k.Fz=function(){return!1};
g.k.tC=function(a,b){this.rh=a.Sm;if(0==this.hf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.ug=this.rh;$6(c,2);return}this.Rm=c[0];this.nm=c[1]}else c=this.o,c.ug=this.rh,$6(c,2);else if(2==this.hf)if(this.Dr)E6(7),this.Ju=(0,g.E)();else if("11111"==b){if(E6(6),this.Dr=!0,this.Fp=(0,g.E)(),c=this.Fp-this.Gz,!g.le||g.Qd(10)||500>c)this.rh=200,this.Be.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Fp=this.Ju=(0,g.E)(),this.Dr=!1};
g.k.Zp=function(){this.rh=this.Be.Sm;if(this.Be.dg)0==this.hf?this.nm?(this.hf=1,UAa(this)):(this.hf=2,O6(this)):2==this.hf&&((!g.le||g.Qd(10)?!this.Dr:200>this.Ju-this.Fp)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.hf?E6(9):2==this.hf&&E6(10);var a=this.o;this.Be.getLastError();a.ug=this.rh;$6(a,2)}};
g.k.ho=function(){return this.o.ho()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Uf=function(a){this.o.Uf(a)};g.Ua(P6,g.mf);var ZAa=/^https?$/i,MCa=["POST","PUT"];g.k=P6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ga=b;this.Y=!1;this.A=!0;this.o=this.T?IAa(this.T):IAa(S8);this.U=this.T?this.T.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.pC,this);try{c6(S6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){c6(S6(this,"Error opening Xhr: "+f.message));YAa(this,f);return}a=
c||"";var e=this.headers.clone();d&&hAa(d,function(f,h){e.set(h,f)});
d=g.cb(e.df(),WAa);c=g.v.FormData&&a instanceof g.v.FormData;!g.fb(MCa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.fa&&(this.o.responseType=this.fa);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{aBa(this),0<this.G&&(this.R=VAa(this.o),c6(S6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Hz,this)):this.N=g.Yf(this.Hz,this.G,this)),c6(S6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){c6(S6(this,"Send error: "+f.message)),YAa(this,f)}};
g.k.Hz=function(){"undefined"!=typeof g.C1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,S6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(S6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),Q6(this,!0));P6.uc.X.call(this)};
g.k.pC=function(){this.ha()||(this.aa||this.I||this.C?$Aa(this):this.MM())};
g.k.MM=function(){$Aa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=U6.prototype;g.k.Xk=null;g.k.Gm=null;g.k.ne=null;g.k.Ec=null;g.k.eu=null;g.k.Ip=null;g.k.hy=null;g.k.Yp=null;g.k.Bn=0;g.k.sK=0;g.k.Kd=null;g.k.gi=null;g.k.ah=null;g.k.mj=null;g.k.bi=null;g.k.ts=null;g.k.ol=-1;g.k.nA=-1;g.k.ug=-1;g.k.Qk=0;g.k.Ck=0;g.k.ij=8;var a7=new g.mf;g.Ua(cBa,g.Me);g.Ua(dBa,g.Me);g.Ua(eBa,g.Me);g.k=U6.prototype;g.k.connect=function(a,b,c,d,e){E6(0);this.eu=b;this.Gm=c||{};d&&void 0!==e&&(this.Gm.OSID=d,this.Gm.OAID=e);this.F?(J6((0,g.x)(this.zy,this,a),100),iBa(this)):this.zy(a)};
g.k.zy=function(a){this.bi=new TAa(this);this.bi.fu=this.Xk;this.bi.u=this.C;this.bi.connect(a)};
g.k.Fz=function(){return 0==this.o};
g.k.BC=function(a){this.gi=null;lBa(this,a)};
g.k.AC=function(){this.ah=null;this.Ec=new A6(this,this.A,"rpc",this.G);this.Ec.Aj=this.Xk;this.Ec.hu=0;var a=this.hy.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.A);Z5(a,"CI",this.ts?"0":"1");Z5(a,"AID",this.ol);V6(this,a);if(!g.le||g.Qd(10))Z5(a,"TYPE","xmlhttp"),B6(this.Ec,a,!0,this.Yp,!1);else{Z5(a,"TYPE","html");var b=this.Ec,c=!!this.Yp;b.Sl=3;b.Yh=$5(a.clone());PAa(b,c)}};
g.k.tC=function(a,b){if(0!=this.o&&(this.Ec==a||this.ne==a))if(this.ug=a.Sm,this.ne==a&&3==this.o)if(7<this.ij){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.ah){if(this.Ec)if(this.Ec.Ml+3E3<this.ne.Ml)X6(this),this.Ec.cancel(),this.Ec=null;else break a;Z6(this);E6(19)}}else this.nA=c[1],0<this.nA-this.ol&&37500>c[2]&&this.ts&&0==this.Ck&&!this.mj&&(this.mj=J6((0,g.x)(this.SK,this),6E3));else $6(this,11)}else b!=LCa.KQ.o&&$6(this,11);else if(this.Ec==
a&&X6(this),!g.lc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ol=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Yp=e[2],e=e[3],null!=e?this.ij=e:this.ij=6,this.o=3,this.Kd&&this.Kd.ty(),this.hy=M6(this,this.ho()?this.Yp:null,this.eu),mBa(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Kd&&this.Kd.sy(e),this.Ck=0)}}};
g.k.SK=function(){null!=this.mj&&(this.mj=null,this.Ec.cancel(),this.Ec=null,Z6(this),E6(20))};
g.k.Zp=function(a){if(this.Ec==a){X6(this);this.Ec=null;var b=2}else if(this.ne==a)this.ne=null,b=1;else return;this.ug=a.Sm;if(0!=this.o)if(a.dg)1==b?(b=(0,g.E)()-a.Ml,a7.dispatchEvent(new dBa(a7,a.hk?a.hk.length:0,b,this.Qk)),W6(this),this.B.length=0):mBa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ug)){if(d=1==b)this.ne||this.gi||1==this.o||2<=this.Qk?d=!1:(this.gi=J6((0,g.x)(this.BC,this,a),nBa(this,this.Qk)),this.Qk++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.k.kG=function(a){if(!g.fb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.bP=function(a){a?E6(2):(E6(1),oBa(this,8))};
g.k.zt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Z=!1;return a};
g.k.isActive=function(){return!!this.Kd&&this.Kd.isActive(this)};
g.k.Uf=function(a){a7.dispatchEvent(new eBa(a7,a))};
g.k.ho=function(){return!(!g.le||g.Qd(10))};
g.k=pBa.prototype;g.k.ty=function(){};
g.k.sy=function(){};
g.k.ry=function(){};
g.k.it=function(){};
g.k.dz=function(){return{}};
g.k.isActive=function(){return!0};g.k=qBa.prototype;g.k.isEmpty=function(){return g.gb(this.o)&&g.gb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.fb(this.o,a)||g.fb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Jua)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.lb(this.u,a)};
g.k.Xd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(b7,g.A);g.k=b7.prototype;g.k.AN=function(){this.Nd=Math.min(3E5,2*this.Nd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Nd+15E3*Math.random();this.o.kb(a);this.u=(0,g.E)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Nd=5E3};g.Ua(c7,pBa);g.k=c7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Ji=function(a){return this.A.Bj(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Sc||(this.Sc=!0,g.Ke(this.A),tBa(this),g.Ke(this.u),this.u=null,this.R=function(){return""})};
g.k.ha=function(){return this.Sc};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.U),e=this.o;e&&(e.Kd=null);d.Kd=this;this.o=d;d7(this);e?this.o.connect(a,b,this.F,e.A,e.ol):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Xb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&(d7(this),jBa(this.o,c))};
g.k.ty=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)jBa(this.o,a[b])}this.S("handlerOpened")};
g.k.ry=function(a){var b=2==a&&401==this.o.ug;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.it=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.dz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Xb(a,this.C);return a};
g.k.sy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),hBa(this.o)):this.S("handlerMessage",new rBa(a[0],a[1]))};
g.k.GO=function(){this.u.isActive();var a=this.o,b=0;a.Ec&&b++;a.ne&&b++;0==b&&this.connect(this.C,this.B)};f7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.C=function(a){a(Error("request timed out"))};var BBa=(0,g.E)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Ua(n7,g.O);n7.prototype.Me=function(){return this.screens};
n7.prototype.contains=function(a){return!!k6(this.screens,a)};
n7.prototype.get=function(a){return a?l6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.F,a)};g.t(o7,g.O);g.k=o7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.BE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.Jo(this.Ka),this.Ka=NaN)};
g.k.X=function(){this.stop();g.O.prototype.X.call(this)};
g.k.BE=function(){this.Ka=NaN;this.o=g.rq(g7(this.F,"/pairing/get_screen"),{method:"POST",Gb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.DP,this),onError:(0,g.x)(this.CP,this),Se:(0,g.x)(this.EP,this)})};
g.k.DP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.S("pairingComplete",new f6(c))};
g.k.CP=function(a){this.o=null;a.status&&404==a.status?this.u>=NCa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=NCa[this.u],this.Ka=g.Ho((0,g.x)(this.BE,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.EP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var NCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.S("screenChange");!g.at("yt-remote-lounge-token-expiration")&&FBa(this);g.Jo(this.o);this.o=g.Ho((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);CBa(this,a);r7(this,!1);this.S("screenChange");b(a);a.token||FBa(this)};
g.k.remove=function(a,b){var c=p7(this);EBa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.qs=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.Jo(this.o);q7.uc.X.call(this)};
g.k.XG=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.F,"Missed "+b+" lounge tokens.")};
g.k.WG=function(a){j7(this.F,"Requesting lounge tokens failed: "+a)};g.t(t7,g.O);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.at("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.E)()-144E5<a?0:a)?v7(this):(this.B=(0,g.E)()+3E5,g.$s("yt-remote-fast-check-period",this.B),this.Yv())};
g.k.isEmpty=function(){return g.Rb(this.o)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Db(this.o,function(c,d){return c&&!!l6(a,d)},this);
u7(this,b)};
g.k.X=function(){g.Jo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.O.prototype.X.call(this)};
g.k.Yv=function(){g.Jo(this.A);this.A=NaN;this.u&&this.u.abort();var a=IBa(this);if(b6(a)){var b=g7(this.C,"/pairing/get_screen_availability");this.u=h7(this.C,b,{lounge_token:g.Lb(a).join(",")},(0,g.x)(this.kN,this,a),(0,g.x)(this.jN,this))}else u7(this,{}),v7(this)};
g.k.kN=function(a,b){this.u=null;var c=g.Lb(IBa(this));if(g.zb(c,g.Lb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.qc("Changing Screen set during request."),this.Yv()};
g.k.jN=function(a){this.qc("Screen availability failed: "+a);this.u=null;v7(this)};
g.k.qc=function(a){j7("OnlineScreenService",a)};g.Ua(w7,n7);g.k=w7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.qs=function(a,b,c,d){this.u.contains(a)?this.u.qs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.F,a),d(Error(a)))};
g.k.Me=function(a){return a?this.screens:g.ob(this.screens,(0,g.ye)(this.A,function(b){return!this.contains(b)},this))};
g.k.CE=function(){return(0,g.ye)(this.Me(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.DE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Ke(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Ke(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.GP=function(a,b,c,d){g.rq(g7(this.C,"/pairing/get_screen"),{method:"POST",Gb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new f6(f.screen||{});if(!h.name||MBa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);MBa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Se:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Ke(this.u);g.Ke(this.o);w7.uc.X.call(this)};
g.k.eH=function(){NBa(this);this.S("screenChange");this.o.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Ua(z7,g.O);g.k=z7.prototype;g.k.getScreen=function(){return this.I};
g.k.sr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Re=function(a){this.ha()||(a&&A7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){j7(this.U,a)};
g.k.FE=function(){return null};
g.k.kw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.kw("");z7.uc.X.call(this)};g.t(B7,z7);g.k=B7.prototype;g.k.jw=function(a){if(this.u){if(this.u==a)return;A7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);PBa(this)};
g.k.pl=function(a){this.info("launchWithParams no-op for Cast: "+g.Nk(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Re()},this),(0,g.x)(function(){this.Re(Error("Failed to stop receiver app."))},this)):this.Re(Error("Stopping cast device witout session."))};
g.k.kw=function(){};
g.k.X=function(){this.info("disposeInternal");g.Jo(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;z7.prototype.X.call(this)};
g.k.YN=function(a,b){if(!this.ha())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Nk(c));switch(d){case "mdxSessionStatus":OBa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.yz=function(a,b,c,d){LBa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ho((0,g.x)(this.yz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.FE=function(){return this.u};
g.k.HP=function(a){this.ha()||a||(A7(this,"Cast session died."),this.Re())};g.t(C7,z7);g.k=C7.prototype;g.k.jw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.pl=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.Ka;g.Jo(this.C);this.A?this.A.stop((0,g.x)(this.Re,this,null),(0,g.x)(this.Re,this,"Failed to stop DIAL device.")):this.Re()};
g.k.X=function(){this.u();this.u=g.Ka;g.Jo(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;z7.prototype.X.call(this)};
g.k.KP=function(a){this.ha()||a||(A7(this,"DIAL session died."),this.u(),this.u=g.Ka,this.Re())};
g.k.ru=function(a){this.N=j6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,RBa(this));a(b);QBa(this)}else this.F=(0,g.x)(function(){g.Jo(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,RBa(this));a(c);QBa(this)},this),this.C=g.Ho((0,g.x)(function(){this.F()},this),100)};
g.k.uH=function(a,b,c){LBa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.sr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.ru(b,c)},this),(0,g.x)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.ru(b,c)},this))};g.t(D7,z7);D7.prototype.stop=function(){this.Re()};
D7.prototype.jw=function(){};
D7.prototype.pl=function(){g.Jo(this.u);this.u=NaN;var a=l6(this.M.Me(),this.o.label);a?this.sr(a):this.Re(Error("No such screen"))};
D7.prototype.X=function(){g.Jo(this.u);this.u=NaN;z7.prototype.X.call(this)};g.t(E7,g.O);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.SM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.wC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.nL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),yBa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.EE,this)),this.A=TBa(this),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(h){this.qc("Failed to set initial custom receivers: "+g.Nk(h))},this)),this.S("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.x)(function(h){this.qc("Failed to initialize API: "+g.Nk(h));
b(!1)},this))};
g.k.MO=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.o.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=l6(this.u.Me(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=SBa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ka,(0,g.x)(function(e){this.qc("Failed to set initial custom receivers: "+g.Nk(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.u,d),!0)}this.o.kw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.NO=function(a){this.ha()?this.qc("Setting connection data on disposed cast v2"):this.o?this.o.pl(a):this.qc("Setting connection data without a session")};
g.k.JP=function(){this.ha()?this.qc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.wC,this),(0,g.x)(this.nN,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.EE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=vBa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.lb(b||[],a);g.Ke(this.o);g.O.prototype.X.call(this)};
g.k.qc=function(a){j7("Controller",a)};
g.k.yC=function(a,b){this.o==a&&(b||H7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.OM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.u,a));break;default:this.qc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.qc("Stopping receiver w/o session: "+a.friendlyName)}else this.qc("onReceiverAction_ called without receiver.")};
g.k.nL=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.qc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.qc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return F7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.qc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.uH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.ru,b))};
g.k.wC=function(a){if(!this.ha()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.u,b),!0);else{this.qc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=l6(this.u.Me(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ke(this.o),this.o=new B7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.yC,this,this.o)),this.o.pl(null));this.o.jw(a)}}};
g.k.IP=function(){return this.o?this.o.FE():null};
g.k.nN=function(a){this.ha()||(this.qc("Failed to estabilish a session: "+g.Nk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.SM=function(a){F7("Receiver availability updated: "+a);if(!this.ha()){var b=G7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.S("yt-remote-cast2-availability-change",G7(this))}};
g.k.EE=function(){this.ha()||(this.A=TBa(this),F7("Updating custom receivers: "+g.Nk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(){this.qc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.NO;E7.prototype.setConnectedScreenStatus=E7.prototype.MO;E7.prototype.stopSession=E7.prototype.JP;E7.prototype.getCastSession=E7.prototype.IP;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.vg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.ub=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.t($7,g.O);g.k=$7.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ub()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.S("remotePlayerChange")}else b8(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.S("remotePlayerChange")}else b8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.qc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.qc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Sa(this.setVolume,a,b))};
g.k.AE=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Nk(b.style),g.Xb(d,c.o));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Sa(this.AE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();e8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;c8(this,d)}else b8(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Nk(h));e8(this,"setPlaylist",m);d||c8(this,l)};
g.k.yr=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Sa(this.yr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Sa(this.nextVideo,a,b))};
g.k.My=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.My)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.O.prototype.dispose.call(this)};
g.k.X=function(){fCa(this);this.B=null;this.C.clear();Z7(this,null);g.O.prototype.X.call(this)};
g.k.ex=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.gb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.KM=function(a,b){this.S(a,b)};
g.k.YK=function(a){if(!a)this.Fn(null),Z7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.k.Fn=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),gCa(this),this.S("remotePlayerChange")};
g.k.XK=function(a){a?(gCa(this),this.S("remotePlayerChange")):this.Fn(null)};
g.k.Ew=function(){e8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.gL=function(){var a=cCa();a&&Z7(this,a)};
g.k.qc=function(a){j7("CP",a)};g.t(g8,g.O);g.k=g8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=h||0;this.jb.state=3;V7(this.jb,m);this.B="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Nk(l));this.o.connect({method:"setPlaylist",
params:g.Nk(l)},a,tAa())}else h8("Connecting without params"),this.o.connect({},a,tAa());iCa(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),i8(this,3));g.O.prototype.dispose.call(this)};
g.k.X=function(){j8(this);l8(this);k8(this);g.Jo(this.G);this.G=NaN;g.Jo(this.I);this.I=NaN;this.A=null;g.ep(this.U);this.U.length=0;this.o.dispose();g.O.prototype.X.call(this);this.B=this.F=this.u=this.jb=this.o=null};
g.k.PG=function(){this.Lk(2)};
g.k.cL=function(){h8("Channel opened");this.R&&(this.R=!1,k8(this),this.N=g.Ho((0,g.x)(function(){h8("Timing out waiting for a screen.");this.Lk(1)},this),15E3));
xAa(sBa(this.o),this.T)};
g.k.ZK=function(){h8("Channel closed");isNaN(this.C)?q6(!0):q6();this.dispose()};
g.k.aL=function(a){q6();isNaN(this.Nm())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,h8("Channel error: "+a+" with reconnection in "+this.Nm()+" ms"),i8(this,2))};
g.k.bL=function(a){a.params?h8("Received: action="+a.action+", params="+g.Nk(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Ic)(a,function(c){return new e6(c)});
a=!!g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
lCa(this,a);break;case "loungeScreenDisconnected":g.nb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
lCa(this,!1);break;case "remoteConnected":var b=new e6(x6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1})||dAa(this.u,b);
break;case "remoteDisconnected":b=new e6(x6(a.params.device));g.nb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":nCa(this,a);break;case "nowPlaying":pCa(this,a);break;case "onStateChange":oCa(this,a);break;case "onAdStateChange":qCa(this,a);break;case "onVolumeChanged":rCa(this,a);break;case "onSubtitlesTrackChanged":mCa(this,a);break;case "nowAutoplaying":sCa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":tCa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.k.CO=function(){if(this.A){var a=this.A;this.A=null;this.jb.videoId!=a&&m8(this,"getNowPlaying")}};
g.k.FG=function(){var a=3;this.ha()||(a=0,isNaN(this.Nm())?e7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Lk=function(a){h8("Disconnecting with "+a);j8(this);this.S("beforeDisconnect",a);1==a&&q6();tBa(this.o,a);this.dispose()};
g.k.DG=function(){var a=this.jb;this.A&&(a=this.jb.clone(),X7(a,this.A,a.index));return Y7(a)};
g.k.OO=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.A=b.videoId,g.Jo(this.G),this.G=g.Ho((0,g.x)(this.CO,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.playerState==b.playerState&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&W7(this.jb)==W7(b)&&g.Nk(this.jb.o)==g.Nk(b.o)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.wz=function(){var a=this.o.F.id,b=g.cb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Nm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.k.sG=function(){return this.B||"UNSUPPORTED"};
g.k.tG=function(){return this.F||""};
g.k.BP=function(){if(!isNaN(this.Nm())){var a=this.o.u;g.zn(a.o);a.start()}};
g.k.KO=function(a,b){m8(this,a,b);kCa(this)};
g.k.zE=function(){var a=g.zq("SID","")||"",b=g.zq("SAPISID","")||"";if(!a&&!b)return"";a=g.vg(g.cg(a),2);b=g.vg(g.cg(b),2);return g.vg(g.cg(a+","+b),2)};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.Ji;g8.prototype.getProxyState=g8.prototype.FG;g8.prototype.disconnect=g8.prototype.Lk;g8.prototype.getPlayerContextData=g8.prototype.DG;g8.prototype.setPlayerContextData=g8.prototype.OO;g8.prototype.getOtherConnectedRemoteId=g8.prototype.wz;g8.prototype.getReconnectTimeout=g8.prototype.Nm;g8.prototype.getAutoplayMode=g8.prototype.sG;g8.prototype.getAutoplayVideoId=g8.prototype.tG;g8.prototype.reconnect=g8.prototype.BP;
g8.prototype.sendMessage=g8.prototype.KO;g8.prototype.getXsrfToken=g8.prototype.zE;g.t(n8,n7);g.k=n8.prototype;g.k.Me=function(a){return this.Md.$_gs(a)};
g.k.contains=function(a){return!!this.Md.$_c(a)};
g.k.get=function(a){return this.Md.$_g(a)};
g.k.start=function(){this.Md.$_st()};
g.k.add=function(a,b,c){this.Md.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Md.$_r(a,b,c)};
g.k.qs=function(a,b,c,d){this.Md.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Md.$_ubk(this.o[a]);this.o.length=0;this.Md=null;n7.prototype.X.call(this)};
g.k.FP=function(){this.S("screenChange")};
g.k.oM=function(){this.S("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.GP;w7.prototype.$_gsppc=w7.prototype.DE;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.qs;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Me;w7.prototype.$_gos=w7.prototype.CE;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Ji;var G8=null,F8=!1,o8=null,p8=null,E8=null,t8=[];g.t(H8,g.A);g.k=H8.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.ab;a.unsubscribe("proxyStateChange",this.sC,this);a.unsubscribe("remotePlayerChange",this.Mn,this);a.unsubscribe("remoteQueueChange",this.tr,this);a.unsubscribe("previousNextChange",this.oC,this);a.unsubscribe("nowAutoplaying",this.kC,this);a.unsubscribe("autoplayDismissed",this.KB,this);this.ab=this.module=null};
g.k.SA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ab.o)if(I8(this)){if(!a8(this.ab).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.ab).ub()?this.ab.pause():this.ab.play();break;case "control_play":this.ab.play();break;case "control_pause":this.ab.pause();break;case "control_seek":this.F.CA(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();K8(this,0===c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.WK=function(a){this.G.LG(a)};
g.k.lP=function(a){this.SA("control_subtitles_set_track",g.Rb(a)?null:a)};
g.k.MD=function(){var a=this.H.getOption("captions","track");g.Rb(a)||J8(this,a)};
g.k.Yb=function(a){this.module.Yb(a,this.H.getVideoData().lengthSeconds)};
g.k.aC=function(a){if(I8(this)){this.ab.unsubscribe("remotePlayerChange",this.Mn,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.ab);if(b!==c.volume||a!==c.muted)this.ab.setVolume(b,a),this.I.start();this.ab.subscribe("remotePlayerChange",this.Mn,this)}};
g.k.PL=function(){g.Rb(this.A)||FCa(this,this.A);this.B=!1};
g.k.sC=function(a,b){this.u.stop();2===b&&this.JD()};
g.k.Mn=function(){if(I8(this)){this.o.stop();var a=a8(this.ab);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.md=1;break;case 1082:case 1083:this.module.md=0;break;default:this.module.md=-1}switch(a.playerState){case 1081:case 1:this.Qc(new g.aG(8));this.ID();break;case 1085:case 3:this.Qc(new g.aG(9));break;case 1083:case 0:this.Qc(new g.aG(2));this.F.stop();this.Yb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Qc(new g.aG(4));break;case 2:this.Qc(new g.aG(4));
this.Yb(W7(a));break;case -1:this.Qc(new g.aG(64));break;case -1E3:this.Qc(new g.aG(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a8(this.ab).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,FCa(this,a));a=a8(this.ab);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.mE()}else ECa(this)};
g.k.oC=function(){this.H.S("mdxpreviousnextchange")};
g.k.tr=function(){I8(this)||ECa(this)};
g.k.kC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.KB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){I8(this)&&this.ab.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.ab).playerState?K8(this,a):b&&this.ab.seekTo(a)};
g.k.mE=function(){if(I8(this)){var a=a8(this.ab);this.events.rb(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.aC)}};
g.k.ID=function(){this.o.stop();if(!this.ab.ha()){var a=a8(this.ab);a.ub()&&this.Qc(new g.aG(8));this.Yb(W7(a));this.o.start()}};
g.k.JD=function(){this.u.stop();this.o.stop();var a=this.ab.B.getReconnectTimeout();2==this.ab.o&&!isNaN(a)&&this.u.start()};
g.k.Qc=function(a){this.u.stop();var b=this.C;if(!g.fG(b,a)){var c=g.T(a,2);c!==g.T(this.C,2)&&g.XT(this.H.app,c);this.C=a;HCa(this.module,b,a)}};g.t(L8,g.U);L8.prototype.Zb=function(){this.o.show()};
L8.prototype.Sa=function(){this.o.hide()};
L8.prototype.u=function(){g.rO("https://support.google.com/youtube/answer/7640706")};
L8.prototype.A=function(){d6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(M8,g.U);M8.prototype.Zb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){d6("mdx-privacy-popup-cancel");this.Sa()};
M8.prototype.A=function(){d6("mdx-privacy-popup-confirm");this.Sa()};g.t(N8,g.U);N8.prototype.u=function(a){GCa(this,a.state)};g.t(O8,g.FR);O8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Ri=g.Bb(a,this.o,this),g.HR(this,(0,g.Ic)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Pb(this.o(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.o=function(a){return a.key};
O8.prototype.Sf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Ri[a].name};
O8.prototype.zd=function(a){g.FR.prototype.zd.call(this,a);this.H.setOption("remote","currentReceiver",this.Ri[a]);this.Ma.Sa()};g.t(P8,g.QN);g.k=P8.prototype;
g.k.create=function(){yCa(g.py(this.player.O()));this.subscriptions.push(g.Oo("yt-remote-before-disconnect",this.UK,this));this.subscriptions.push(g.Oo("yt-remote-connection-change",this.TM,this));this.subscriptions.push(g.Oo("yt-remote-receiver-availability-change",this.qC,this));this.subscriptions.push(g.Oo("yt-remote-auto-connect",this.RM,this));this.subscriptions.push(g.Oo("yt-remote-receiver-resumed",this.QM,this));this.subscriptions.push(g.Oo("mdx-privacy-popup-confirm",this.qO,this));this.subscriptions.push(g.Oo("mdx-privacy-popup-cancel",
this.pO,this));this.subscriptions.push(g.Oo("mdx-manual-pairing-popup-ok",this.MH,this));this.qC()};
g.k.load=function(){this.player.cancelPlayback();g.QN.prototype.load.call(this);this.ng=new H8(this,this.player,this.ab);var a=(a=DCa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.Yb(a);HCa(this,this.Ub,this.Ub);g.eU(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.di=this.Pf;g.Le(this.ng,this.ab);this.ab=this.ng=null;g.QN.prototype.unload.call(this);g.eU(this.player.app,5);Q8(this)};
g.k.X=function(){g.Po(this.subscriptions);g.QN.prototype.X.call(this)};
g.k.Ig=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.ng.SA.apply(this.ng,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.md};
g.k.HG=function(){return this.loaded?this.ng.suggestion:null};
g.k.vg=function(){return this.ab?a8(this.ab).vg:!1};
g.k.hasNext=function(){return this.ab?a8(this.ab).hasNext:!1};
g.k.Yb=function(a,b){this.oA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.oA};
g.k.getProgressState=function(){var a=a8(this.ab),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ld():!a.isAdPlaying()&&this.player.ld(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+U7(a):a.B,isAtLiveHead:1>=(a.A?a.u+U7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+U7(a):a.u,seekableStart:0<a.C?a.C+
U7(a):a.C}};
g.k.nextVideo=function(){this.ab&&this.ab.nextVideo()};
g.k.yr=function(){this.ab&&this.ab.yr()};
g.k.UK=function(a){1===a&&(this.Lv=this.ab?a8(this.ab):null)};
g.k.TM=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.di;this.loaded&&this.unload();this.ab=a;this.Lv=null;b.key!==this.Pf.key&&(this.di=b,this.load())}else g.Ke(this.ab),this.ab=null,this.loaded&&(this.unload(),(a=this.Lv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.qC=function(){this.Ri=[this.Pf].concat(ACa());var a=z8()||this.Pf;R8(this,a);this.player.oa("onMdxReceiversChange")};
g.k.RM=function(){var a=z8();R8(this,a)};
g.k.QM=function(){this.di=z8()};
g.k.qO=function(){this.Nn=!0;Q8(this);F8=!1;G8&&B8(G8,1);G8=null};
g.k.pO=function(){this.Nn=!1;Q8(this);R8(this,this.Pf);this.di=this.Pf;F8=!1;G8=null;this.player.playVideo()};
g.k.MH=function(){this.Cq=!0;Q8(this);g.$s("yt-remote-manual-pairing-warning-shown",!0,2592E3);F8=!1;G8&&B8(G8,1);G8=null};
g.k.hd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Ri;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():R8(this,b)),this.loaded?this.di:this.Pf;case "quickCast":return 2===this.Ri.length&&"cast-selector-receiver"===this.Ri[1].key?(b&&Q7(),!0):!1}};
g.k.Ew=function(){this.ab.Ew()};
g.k.cg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.aO.remote=P8;})(_yt_player);
